[build]
  command = "npm install"
  publish = "../frontend/dist" # Corrected path
  base    = "backend"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200